In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn import metrics
import tensorflow as tf

In [2]:
df = pd.read_csv("taitanic.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [3]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [4]:
train_df = df.drop(["PassengerId", "Name", "Ticket"], axis= 1)

In [5]:
train_df.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         0       3    male  22.0      1      0   7.2500   NaN        S
1         1       1  female  38.0      1      0  71.2833   C85        C
2         1       3  female  26.0      0      0   7.9250   NaN        S
3         1       1  female  35.0      1      0  53.1000  C123        S
4         0       3    male  35.0      0      0   8.0500   NaN        S

In [6]:
print(f"Train :\n {train_df.isna().sum()}")

Train :
 Survived      0
Pclass        0
Sex           0
Age         177
SibSp         0
Parch         0
Fare          0
Cabin       687
Embarked      2
dtype: int64

In [7]:
male_mean_age = train_df[train_df["Sex"] == "male"]["Age"].mean()
female_mean_age = train_df[train_df["Sex"] == "female"]["Age"].mean()

print("female mean age : %1.0f" %female_mean_age)
print("male mean age : %1.0f" %male_mean_age)

female mean age : 28
male mean age : 31

In [8]:
train_df.loc[(train_df["Sex"] == "male") & (train_df["Age"].isnull()), "Age"] = male_mean_age
train_df.loc[(train_df["Sex"] == "female") & (train_df["Age"].isnull()), "Age"] = female_mean_age

In [9]:
mean_fare = train_df["Fare"].mean()

In [10]:
train_df["Cabin"] = train_df["Cabin"].fillna("X")
train_df["Embarked"] = train_df["Embarked"].fillna("S")